export interface Question {
  id: number;
  question: string;
  type?: "truth" | "dare"; 
}

export interface MiniGameSet {
  title: string;
  questions: Question[];
}

// TRUTH OR DARE
export const truthOrDare: MiniGameSet = {
  title: "Truth or Dare",
  questions: [
    { id: 1, question: "What’s your biggest fear?", type: "truth" },
    { id: 2, question: "Who was your first crush?", type: "truth" },
    { id: 3, question: "What’s the most embarrassing thing you’ve ever done?", type: "truth" },
    { id: 4, question: "What’s a secret you’ve never told anyone?", type: "truth" },
    { id: 5, question: "What’s your guilty pleasure?", type: "truth" },
    { id: 6, question: "Who would you call if you were in trouble?", type: "truth" },
    { id: 7, question: "What’s your most-used emoji?", type: "truth" },
    { id: 8, question: "Have you ever lied to a friend?", type: "truth" },
    { id: 9, question: "What’s something you regret doing?", type: "truth" },
    { id: 10, question: "If you could change one thing about yourself, what would it be?", type: "truth" },
    { id: 11, question: "Who in this room do you trust the most?", type: "truth" },
    { id: 12, question: "Have you ever cheated in a game?", type: "truth" },
    { id: 13, question: "What’s your dream job?", type: "truth" },
    { id: 14, question: "What’s something you’re really bad at?", type: "truth" },
    { id: 15, question: "Who would you like to switch lives with for a day?", type: "truth" },
    { id: 16, question: "What’s the weirdest food you’ve tried?", type: "truth" },
    { id: 17, question: "What’s one thing you can’t live without?", type: "truth" },
    { id: 18, question: "Have you ever kept a secret from your parents?", type: "truth" },
    { id: 19, question: "What’s your favorite childhood memory?", type: "truth" },
    { id: 20, question: "What’s the most childish thing you still do?", type: "truth" },
    { id: 21, question: "What’s one thing you wish people knew about you?", type: "truth" },
    { id: 22, question: "What’s your biggest insecurity?", type: "truth" },
    { id: 23, question: "Have you ever cried in public?", type: "truth" },
    { id: 24, question: "What’s your worst habit?", type: "truth" },
    { id: 25, question: "What’s one goal you haven’t achieved yet?", type: "truth" },

    { id: 26, question: "Sing a song loudly for 10 seconds.", type: "dare" },
    { id: 27, question: "Do your best celebrity impression.", type: "dare" },
    { id: 28, question: "Spin around 10 times and walk straight.", type: "dare" },
    { id: 29, question: "Speak in an accent for the next 3 rounds.", type: "dare" },
    { id: 30, question: "Do 10 jumping jacks.", type: "dare" },
    { id: 31, question: "Post a funny selfie.", type: "dare" },
    { id: 32, question: "Act like a cat for 30 seconds.", type: "dare" },
    { id: 33, question: "Talk without moving your lips for one minute.", type: "dare" },
    { id: 34, question: "Let the person next to you write something on your hand.", type: "dare" },
    { id: 35, question: "Dance to a random song.", type: "dare" },
    { id: 36, question: "Imitate someone in the group.", type: "dare" },
    { id: 37, question: "Share your last photo taken.", type: "dare" },
    { id: 38, question: "Sing the chorus of your favorite song.", type: "dare" },
    { id: 39, question: "Tell a joke — if no one laughs, do 5 push-ups.", type: "dare" },
    { id: 40, question: "Text a random emoji to your last contact.", type: "dare" },
    { id: 41, question: "Pretend to be a robot for 30 seconds.", type: "dare" },
    { id: 42, question: "Balance something on your head for 10 seconds.", type: "dare" },
    { id: 43, question: "Act out your favorite movie scene.", type: "dare" },
    { id: 44, question: "Say something nice to everyone in the group.", type: "dare" },
    { id: 45, question: "Eat a spoonful of a random sauce.", type: "dare" },
    { id: 46, question: "Let someone tickle you for 10 seconds.", type: "dare" },
    { id: 47, question: "Whisper everything you say for 2 rounds.", type: "dare" },
    { id: 48, question: "Make an animal sound until your next turn.", type: "dare" },
    { id: 49, question: "Compliment the person on your left.", type: "dare" },
    { id: 50, question: "Do a silly dance move for 10 seconds.", type: "dare" },
  ],
};

// THIS OR THAT
export const thisOrThat: MiniGameSet = {
  title: "This or That",
  questions: Array.from(
    [
      "Coffee or Tea?",
      "Summer or Winter?",
      "Cats or Dogs?",
      "Netflix or YouTube?",
      "Beach or Mountains?",
      "Morning or Night?",
      "Texting or Calling?",
      "Chocolate or Vanilla?",
      "Books or Movies?",
      "Pizza or Burger?",
      "Android or iPhone?",
      "Rainy day or Sunny day?",
      "Sneakers or Sandals?",
      "Ice cream or Cake?",
      "City or Countryside?",
      "Gold or Silver?",
      "Comedy or Horror?",
      "Sweet or Spicy?",
      "Jeans or Shorts?",
      "Music or Podcasts?",
      "Instagram or TikTok?",
      "Save money or Spend money?",
      "Travel alone or With friends?",
      "Fiction or Nonfiction?",
      "Early bird or Night owl?",
      "Board games or Video games?",
      "Mountains or Ocean?",
      "Singing or Dancing?",
      "Cooking or Ordering out?",
      "Super strength or Super speed?",
      "Past or Future?",
      "Pen or Pencil?",
      "Train or Plane?",
      "Eat out or Cook at home?",
      "Phone call or Text message?",
      "Sunrise or Sunset?",
      "Comedy or Drama?",
      "Hot chocolate or Coffee?",
      "Instagram or X (Twitter)?",
      "Hoodie or Jacket?",
      "Sneakers or Boots?",
      "Ice cream or Donut?",
      "Big party or Small gathering?",
      "Stay home or Go out?",
      "Art or Science?",
      "Music festival or Movie night?",
      "Shopping online or In-store?",
      "Smart or Funny?",
      "Rich or Famous?",
      "Love or Friendship?",
    ].map((q, i) => ({ id: i + 1, question: q }))
  ),
};

// WHO’S MORE LIKELY TO
export const whosMoreLikely: MiniGameSet = {
  title: "Who’s More Likely To",
  questions: Array.from(
    [
      "Who’s more likely to forget their keys?",
      "Who’s more likely to be late to an event?",
      "Who’s more likely to laugh at the wrong moment?",
      "Who’s more likely to survive a zombie apocalypse?",
      "Who’s more likely to fall asleep during a movie?",
      "Who’s more likely to win the lottery?",
      "Who’s more likely to cry during a sad movie?",
      "Who’s more likely to get lost on a trip?",
      "Who’s more likely to start an argument?",
      "Who’s more likely to become famous?",
      "Who’s more likely to break something accidentally?",
      "Who’s more likely to forget a birthday?",
      "Who’s more likely to adopt a pet?",
      "Who’s more likely to eat dessert first?",
      "Who’s more likely to sing in the shower?",
      "Who’s more likely to make everyone laugh?",
      "Who’s more likely to sleep all day?",
      "Who’s more likely to cancel plans last minute?",
      "Who’s more likely to win a karaoke contest?",
      "Who’s more likely to spend too much money?",
      "Who’s more likely to take the best selfies?",
      "Who’s more likely to text back late?",
      "Who’s more likely to get caught cheating in a game?",
      "Who’s more likely to tell a secret accidentally?",
      "Who’s more likely to run away from a spider?",
      "Who’s more likely to become a teacher?",
      "Who’s more likely to be a millionaire?",
      "Who’s more likely to be the first to apologize?",
      "Who’s more likely to binge-watch a TV show?",
      "Who’s more likely to start dancing in public?",
      "Who’s more likely to get married first?",
      "Who’s more likely to win an argument?",
      "Who’s more likely to prank someone?",
      "Who’s more likely to forget what they were saying?",
      "Who’s more likely to talk during a movie?",
      "Who’s more likely to become a comedian?",
      "Who’s more likely to help a stranger?",
      "Who’s more likely to get a tattoo?",
      "Who’s more likely to spend hours on their phone?",
      "Who’s more likely to go skydiving?",
      "Who’s more likely to sing out loud randomly?",
      "Who’s more likely to get famous on TikTok?",
      "Who’s more likely to forget to charge their phone?",
      "Who’s more likely to cook dinner for everyone?",
      "Who’s more likely to trip while walking?",
      "Who’s more likely to keep a secret forever?",
      "Who’s more likely to laugh until they cry?",
      "Who’s more likely to get lost in a shopping mall?",
      "Who’s more likely to become president?",
      "Who’s more likely to plan a surprise party?",
    ].map((q, i) => ({ id: i + 1, question: q }))
  ),
};

export const miniGames = { truthOrDare, thisOrThat, whosMoreLikely };
